#ChipScope Core Inserter Project File Version 3.0
#Wed Oct 03 18:09:42 CST 2018
Project.device.designInputFile=E\:\\FTP\\1Gsps_ADC_board\\ZJUprojects_cs.ngc
Project.device.designOutputFile=E\:\\FTP\\1Gsps_ADC_board\\ZJUprojects_cs.ngc
Project.device.deviceFamily=17
Project.device.enableRPMs=true
Project.device.outputDirectory=E\:\\FTP\\1Gsps_ADC_board\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=13
Project.filter<0>=cnt_trig_interval*
Project.filter<10>=adpt_comp*
Project.filter<11>=cmd_adpt*
Project.filter<12>=rdy
Project.filter<1>=cnt_trig_interval
Project.filter<2>=chang*
Project.filter<3>=
Project.filter<4>=err*
Project.filter<5>=cnt_tap*
Project.filter<6>=judge*
Project.filter<7>=judeg*
Project.filter<8>=trig_posedge*
Project.filter<9>=*switch*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=Inst_SelfAdpt clk250
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=Inst_SelfAdpt RDY
Project.unit<0>.dataChannel<10>=Inst_SelfAdpt cnt_tap<1>
Project.unit<0>.dataChannel<11>=Inst_SelfAdpt cnt_tap<0>
Project.unit<0>.dataChannel<12>=Inst_SelfAdpt err_tmp<31>
Project.unit<0>.dataChannel<13>=Inst_SelfAdpt err_tmp<30>
Project.unit<0>.dataChannel<14>=Inst_SelfAdpt err_tmp<29>
Project.unit<0>.dataChannel<15>=Inst_SelfAdpt err_tmp<28>
Project.unit<0>.dataChannel<16>=Inst_SelfAdpt err_tmp<27>
Project.unit<0>.dataChannel<17>=Inst_SelfAdpt err_tmp<26>
Project.unit<0>.dataChannel<18>=Inst_SelfAdpt err_tmp<25>
Project.unit<0>.dataChannel<19>=Inst_SelfAdpt err_tmp<24>
Project.unit<0>.dataChannel<1>=Inst_SelfAdpt cmd_adpt_clk200
Project.unit<0>.dataChannel<20>=Inst_SelfAdpt err_tmp<23>
Project.unit<0>.dataChannel<21>=Inst_SelfAdpt err_tmp<22>
Project.unit<0>.dataChannel<22>=Inst_SelfAdpt err_tmp<21>
Project.unit<0>.dataChannel<23>=Inst_SelfAdpt err_tmp<20>
Project.unit<0>.dataChannel<24>=Inst_SelfAdpt err_tmp<19>
Project.unit<0>.dataChannel<25>=Inst_SelfAdpt err_tmp<18>
Project.unit<0>.dataChannel<26>=Inst_SelfAdpt err_tmp<17>
Project.unit<0>.dataChannel<27>=Inst_SelfAdpt err_tmp<16>
Project.unit<0>.dataChannel<28>=Inst_SelfAdpt err_tmp<15>
Project.unit<0>.dataChannel<29>=Inst_SelfAdpt err_tmp<14>
Project.unit<0>.dataChannel<2>=Inst_SelfAdpt adpt_complete
Project.unit<0>.dataChannel<30>=Inst_SelfAdpt err_tmp<13>
Project.unit<0>.dataChannel<31>=Inst_SelfAdpt err_tmp<12>
Project.unit<0>.dataChannel<32>=Inst_SelfAdpt err_tmp<11>
Project.unit<0>.dataChannel<33>=Inst_SelfAdpt err_tmp<10>
Project.unit<0>.dataChannel<34>=Inst_SelfAdpt err_tmp<9>
Project.unit<0>.dataChannel<35>=Inst_SelfAdpt err_tmp<8>
Project.unit<0>.dataChannel<36>=Inst_SelfAdpt err_tmp<7>
Project.unit<0>.dataChannel<37>=Inst_SelfAdpt err_tmp<6>
Project.unit<0>.dataChannel<38>=Inst_SelfAdpt err_tmp<5>
Project.unit<0>.dataChannel<39>=Inst_SelfAdpt err_tmp<4>
Project.unit<0>.dataChannel<3>=Inst_SelfAdpt adpt_switch
Project.unit<0>.dataChannel<40>=Inst_SelfAdpt err_tmp<3>
Project.unit<0>.dataChannel<41>=Inst_SelfAdpt err_tmp<2>
Project.unit<0>.dataChannel<42>=Inst_SelfAdpt err_tmp<1>
Project.unit<0>.dataChannel<43>=Inst_SelfAdpt err_tmp<0>
Project.unit<0>.dataChannel<4>=Inst_SelfAdpt trig_posedge
Project.unit<0>.dataChannel<5>=Inst_SelfAdpt trig_posedge
Project.unit<0>.dataChannel<6>=Inst_SelfAdpt judge_start
Project.unit<0>.dataChannel<7>=Inst_SelfAdpt cnt_tap<4>
Project.unit<0>.dataChannel<8>=Inst_SelfAdpt cnt_tap<3>
Project.unit<0>.dataChannel<9>=Inst_SelfAdpt cnt_tap<2>
Project.unit<0>.dataDepth=16384
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=52
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=Inst_SelfAdpt RDY
Project.unit<0>.triggerChannel<0><10>=Inst_SelfAdpt cnt_tap<1>
Project.unit<0>.triggerChannel<0><11>=Inst_SelfAdpt cnt_tap<0>
Project.unit<0>.triggerChannel<0><12>=Inst_SelfAdpt err_tmp<31>
Project.unit<0>.triggerChannel<0><13>=Inst_SelfAdpt err_tmp<30>
Project.unit<0>.triggerChannel<0><14>=Inst_SelfAdpt err_tmp<29>
Project.unit<0>.triggerChannel<0><15>=Inst_SelfAdpt err_tmp<28>
Project.unit<0>.triggerChannel<0><16>=Inst_SelfAdpt err_tmp<27>
Project.unit<0>.triggerChannel<0><17>=Inst_SelfAdpt err_tmp<26>
Project.unit<0>.triggerChannel<0><18>=Inst_SelfAdpt err_tmp<25>
Project.unit<0>.triggerChannel<0><19>=Inst_SelfAdpt err_tmp<24>
Project.unit<0>.triggerChannel<0><1>=Inst_SelfAdpt cmd_adpt_clk200
Project.unit<0>.triggerChannel<0><20>=Inst_SelfAdpt err_tmp<23>
Project.unit<0>.triggerChannel<0><21>=Inst_SelfAdpt err_tmp<22>
Project.unit<0>.triggerChannel<0><22>=Inst_SelfAdpt err_tmp<21>
Project.unit<0>.triggerChannel<0><23>=Inst_SelfAdpt err_tmp<20>
Project.unit<0>.triggerChannel<0><24>=Inst_SelfAdpt err_tmp<19>
Project.unit<0>.triggerChannel<0><25>=Inst_SelfAdpt err_tmp<18>
Project.unit<0>.triggerChannel<0><26>=Inst_SelfAdpt err_tmp<17>
Project.unit<0>.triggerChannel<0><27>=Inst_SelfAdpt err_tmp<16>
Project.unit<0>.triggerChannel<0><28>=Inst_SelfAdpt err_tmp<15>
Project.unit<0>.triggerChannel<0><29>=Inst_SelfAdpt err_tmp<14>
Project.unit<0>.triggerChannel<0><2>=Inst_SelfAdpt adpt_complete
Project.unit<0>.triggerChannel<0><30>=Inst_SelfAdpt err_tmp<13>
Project.unit<0>.triggerChannel<0><31>=Inst_SelfAdpt err_tmp<12>
Project.unit<0>.triggerChannel<0><32>=Inst_SelfAdpt err_tmp<11>
Project.unit<0>.triggerChannel<0><33>=Inst_SelfAdpt err_tmp<10>
Project.unit<0>.triggerChannel<0><34>=Inst_SelfAdpt err_tmp<9>
Project.unit<0>.triggerChannel<0><35>=Inst_SelfAdpt err_tmp<8>
Project.unit<0>.triggerChannel<0><36>=Inst_SelfAdpt err_tmp<7>
Project.unit<0>.triggerChannel<0><37>=Inst_SelfAdpt err_tmp<6>
Project.unit<0>.triggerChannel<0><38>=Inst_SelfAdpt err_tmp<5>
Project.unit<0>.triggerChannel<0><39>=Inst_SelfAdpt err_tmp<4>
Project.unit<0>.triggerChannel<0><3>=Inst_SelfAdpt adpt_switch
Project.unit<0>.triggerChannel<0><40>=Inst_SelfAdpt err_tmp<3>
Project.unit<0>.triggerChannel<0><41>=Inst_SelfAdpt err_tmp<2>
Project.unit<0>.triggerChannel<0><42>=Inst_SelfAdpt err_tmp<1>
Project.unit<0>.triggerChannel<0><43>=Inst_SelfAdpt err_tmp<0>
Project.unit<0>.triggerChannel<0><44>=Inst_SelfAdpt change_tap_8ns
Project.unit<0>.triggerChannel<0><45>=Inst_SelfAdpt cnt_trig_interval<6>
Project.unit<0>.triggerChannel<0><46>=Inst_SelfAdpt cnt_trig_interval<5>
Project.unit<0>.triggerChannel<0><47>=Inst_SelfAdpt cnt_trig_interval<4>
Project.unit<0>.triggerChannel<0><48>=Inst_SelfAdpt cnt_trig_interval<3>
Project.unit<0>.triggerChannel<0><49>=Inst_SelfAdpt cnt_trig_interval<2>
Project.unit<0>.triggerChannel<0><4>=Inst_SelfAdpt trig_posedge
Project.unit<0>.triggerChannel<0><50>=Inst_SelfAdpt cnt_trig_interval<1>
Project.unit<0>.triggerChannel<0><51>=Inst_SelfAdpt cnt_trig_interval<0>
Project.unit<0>.triggerChannel<0><5>=Inst_SelfAdpt trig_posedge
Project.unit<0>.triggerChannel<0><6>=Inst_SelfAdpt judge_start
Project.unit<0>.triggerChannel<0><7>=Inst_SelfAdpt cnt_tap<4>
Project.unit<0>.triggerChannel<0><8>=Inst_SelfAdpt cnt_tap<3>
Project.unit<0>.triggerChannel<0><9>=Inst_SelfAdpt cnt_tap<2>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=52
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
